apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx-dr
spec:
  host: nginx-service
  trafficPolicy: # Define global subset load balancer.
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: v1
      labels:
        version: V1
      trafficPolicy: # Define specific subset load balancer.
        loadBalancer:
          simple: LEAST_CONN
    - name: v2
      labels:
        version: V2
